# Generated by Django 3.0.8 on 2020-09-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regitration',
            name='Attendance_In_Eval_0',
            field=models.IntegerField(),
        ),
    ]
