# Generated by Django 3.0.8 on 2020-09-14 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_evaluationi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationi',
            old_name='Attendance_In_Eval_0',
            new_name='Attendance_In_Eval_1',
        ),
    ]
