# Generated by Django 3.0.8 on 2020-10-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_evaluationii'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='regitration',
            new_name='evaluation0',
        ),
    ]
