# Generated by Django 3.0.8 on 2020-10-12 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20201012_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation0',
            name='id',
        ),
        migrations.AlterField(
            model_name='evaluation0',
            name='System_Id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evaluationi',
            name='System_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.evaluation0'),
        ),
        migrations.AlterField(
            model_name='evaluationii',
            name='System_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.evaluation0'),
        ),
    ]
