# Generated by Django 3.0.8 on 2020-10-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20201012_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluation0',
            name='id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
