# Generated by Django 3.0.8 on 2020-10-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_evaluation0_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='total',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField()),
                ('total_of_eval0', models.IntegerField()),
                ('total_of_eval1', models.IntegerField()),
                ('total_of_eval2', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
    ]
