# Generated by Django 3.0.8 on 2020-10-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='total',
            new_name='final_Marks',
        ),
        migrations.AlterField(
            model_name='total',
            name='system_id',
            field=models.CharField(max_length=100),
        ),
    ]
