# Generated by Django 3.0.8 on 2020-08-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(max_length=100)),
                ('Project_Title', models.CharField(max_length=100)),
                ('Guide_Name', models.CharField(max_length=100)),
                ('Project_Category', models.CharField(max_length=100)),
                ('Section', models.CharField(max_length=100)),
                ('Project_Passcode', models.CharField(max_length=100)),
                ('Submitted_Sypnosis', models.BooleanField(default=False)),
                ('Screenshot_Of_Approval', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
