# Generated by Django 3.0.8 on 2020-08-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0002_auto_20200826_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Submitted_Sypnosis',
            field=models.CharField(max_length=10),
        ),
    ]
