# Generated by Django 3.0.8 on 2020-08-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0003_auto_20200826_1523'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='evalution_data',
        ),
    ]
