# Generated by Django 3.0.8 on 2020-08-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0004_auto_20200826_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
