# Generated by Django 3.0.8 on 2020-08-26 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0005_auto_20200826_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Screenshot_Of_Approval',
        ),
    ]
