# Generated by Django 3.0.8 on 2020-08-27 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0006_remove_data_screenshot_of_approval'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='projects',
        ),
    ]
