# Generated by Django 3.0.8 on 2020-08-27 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0007_auto_20200827_0620'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='data',
            table='evalution_data',
        ),
    ]
