# Generated by Django 3.0.8 on 2020-08-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0008_auto_20200827_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Screenshot_Of_Approval',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
