# Generated by Django 3.0.8 on 2020-08-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0009_data_screenshot_of_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Phone_Number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='Roll_No',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='System_id',
            field=models.CharField(max_length=100),
        ),
    ]
