# Generated by Django 3.0.8 on 2020-08-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0010_auto_20200827_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Screenshot_Of_Approval',
            field=models.ImageField(upload_to='media/pics'),
        ),
    ]
