# Generated by Django 3.0.8 on 2020-08-31 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0011_auto_20200828_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Screenshot_Of_Approval',
            field=models.ImageField(upload_to='pics/'),
        ),
    ]
