# Generated by Django 3.0.8 on 2020-08-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evalution', '0012_auto_20200831_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Screenshot_Of_Approval',
        ),
    ]
